### PR TITLE
[cleanup] Cleanup sonarlint issues

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by ste-gr** [comment]
Hi @hazendaz,

great thank you! I'll look to it and merge it.

Greetings
Stefan

**Review by ste-gr — APPROVED** [review]
Thank you!

**Comment by hazendaz** [comment]
@ste-gr Wow wasn't expecting so fast here given couple years since repo updated.  I'm looking to get a cut of this working on jakarta namespace.  I'm using this over in https://github.com/hazendaz/displaytag/ that I just rolled out jakarta support officially but the site cannot work yet as this project is still javax.  Was trying to just hard-fork it but thought I'd give it a shot sending a PR with general updates first.  Given you are available here, I'll try to get some more updates in general on javax namespace in coming weeks.  I'm in no real rush so it may be a while but think it will eventually be worthwhile.  Not sure if you have had to deal with jakarta namespace yet but typically what I've been doing is getting as up to date as possible on projects then cutting support branches to rename 'javax' (with unlikely releases at that point) then letting the main go to jakarta.  Anyway its encouraging to see such a quick response so I may not hard fork after all unless you want to keep this just javax.

**Comment by ste-gr** [comment]
Hi @hazendaz,

nice to surprise you 😄. Your project looks very interesting too.
I'm also updating this project for the jakarta namespace to document the [struts1](../../struts1) project. This is the last part, the documentation 😃.
Currently I'm working on updating [tlddoc](../../tlddoc) (dependency of this project) to also handle JakartaEE 9+ tld files (it's done) and do some modernization. I think I will be done with it in the near future. And then I will update this project. But any support is appreciated and welcome.

Greetings
Stefan

**Pull request merged**
